language: node_js
node_js:
  - '8'

dist: trusty
sudo: required
group: deprecated-2017Q4

cache:
  directories:
    - "$HOME/.npm"

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - phantomjs --version
  - npm install -g bower

install:
  - npm install
  - npm rebuild #required for grpc modules to work properly
  - bower install

script:
  - npm test

before_deploy:
  - openssl aes-256-cbc -K $encrypted_9c84f0cea3d3_key -iv $encrypted_9c84f0cea3d3_iv -in fastboot-min.json.enc -out ~\/fastboot-min.json -d

deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
